services:
  postgres:
    image: postgres:15-alpine
    container_name: ssbot_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ssbot_db
    ports:
      - "5432:5432"
    volumes:
      - ssbot_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d ssbot_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  ssbot_postgres_data: